export const ACTIONS = {
    DEFAULT: 'DEFAULT',
    CRYPTO_GET_LISTING_REQUEST: 'CRYPTO_GET_LISTING_REQUEST',
    CRYPTO_GET_LISTING_FAILED: 'CRYPTO_GET_LISTING_FAILED',
    CRYPTO_GET_LISTING_SUCCEED: 'CRYPTO_GET_LISTING_SUCCEED',
    CRYPTO_POPULATE_LISTING_DATA: 'CRYPTO_POPULATE_LISTING_DATA',
    CRYPTO_REFRESH_LISTING_DATA: 'CRYPTO_REFRESH_LISTING_DATA',
    CRYPTO_UPDATE_LISTING_DATA: 'CRYPTO_UPDATE_LISTING_DATA',
}

export const ROUTES = {
    BASE: '/',
    BASE_INTERNAL: '/internal',
    OVERVIEW: '/overview',
    LIQUIDITY: '/liquidity-stats',
}